<a href="https://colab.research.google.com/github/ForemanW/PyTorchLearning/blob/main/0_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating tensors
Tensors are created using torch.tensor() https://pytorch.org/docs/stable/tensors.html



In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
# Get tensor back as Python int
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
vector.ndim
# can remember how many dimensions something has by the number of pairs of square brackets

1

In [12]:
vector.shape

torch.Size([2])

In [16]:
# MATRIX
MATRIX = torch.tensor([[7, 8],[9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [20]:
MATRIX[0]

tensor([7, 8])

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [22]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[2,5,4]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 5, 4]]])

In [23]:
TENSOR.shape
#saying we have 1 3x3 tensor

torch.Size([1, 3, 3])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 5, 4]])

In [26]:
#Individual practice

MYTENSE = torch.tensor([0])

IndexError: index 1 is out of bounds for dimension 0 with size 1